### ISSUE TITLE
Card width extends beyond viewport for long artist names

### ISSUE THREAD

**Issue by mathewantony31** [mathewantony31/sxdiscover#46]
<img width="368" alt="screenshot 2018-03-03 10 21 43" src="https://user-images.githubusercontent.com/12538763/36936552-be7d46d0-1ecc-11e8-961c-fa8ebcac2a12.png">

**Comment by mathewantony31** [comment]
Example artist in the screenshot: http://2018.do512.com/artists/chihiroyamazaki-route14band

**Comment by willstokes** [comment]
Sheeeet. This is because it's all one word.

When the scraper stops running this morning, let me know - and I will see how many bands go over the >8 characters/word limit.

**Potential solutions**
- Split band names manually
- decrease font size for all bands
- decrease font size dynamically & only for one element IF band name character length is over the limit (would involve JS and adding an ID to this particular artist name element to then correspond with something particular in the styling)
- find a way to force-break the band name (insert a dash and line break) for it to fit within the predefined padding

**Comment by mathewantony31** [comment]
nice. my preference is not to change the font size - maybe go for solution 1?
